#!/usr/bin/env php

<?php

defined( 'YII_DEBUG' ) or define( 'YII_DEBUG', TRUE );
defined( 'STDIN' ) or define( 'STDIN', fopen( 'php://stdin', 'r' ) );
defined( 'STDOUT' ) or define( 'STDOUT', fopen( 'php://stdout', 'w' ) );

require( __DIR__ . '/vendor/autoload.php' );
require( __DIR__ . '/vendor/yiisoft/yii2/Yii.php' );
require( __DIR__ . '/config/aliases.php' );

$config = require( __DIR__ . '/config/console.php' );

exit( ( new yii\console\Application( $config ) )->run() );